FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install allure-pytest

COPY services/ ./services/
COPY utils/ ./utils/
COPY logger/ ./logger/
COPY tests/ ./tests/

RUN mkdir -p allure-results

CMD ["pytest", "tests/", "--alluredir=allure-results", "-v"]